### PR TITLE
Julia 1.0 compat

### PR DESCRIPTION
**Pull request by tanmaykm**
- Julia 0.7 and 1.0 compatible
- dropped support 0.5 and 0.6
- dropped Compat.jl

### CODE REVIEW

**Comment by randyzwitch** [comment]
Can you update Travis as well, so that the versions tested match?

**Comment by tanmaykm** [comment]
Had added 0.7 and dropped 0.5-0.6 in travis.yml. What did I miss?

**Comment by randyzwitch** [comment]
Sorry about that, I was reviewing this on my phone. Everything looks good, merging

**Comment by mlhetland** [comment]
Would be great if you could tag a release for this, so a functioning version would be available via `Pkg` (without using `Codecs#master`). Useful for [other projects](https://github.com/dcjones/YAML.jl/pull/54) :-)

**Comment by randyzwitch** [comment]
We are working on it, please be patient 

https://github.com/JuliaLang/METADATA.jl/pull/16489

**Comment by mlhetland** [comment]
Ah, great. Sorry for nagging!

**Pull request merged**
