### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by abhijithch**
Fixes deprecation of `@unix_only` ans `@windows_only`.

### CODE REVIEW

**Comment by randyzwitch** [comment]
+1 

@dcjones Let me know if you want to add me as a contributor here if you need help with maintenance.

**Comment by dcjones** [comment]
Thanks Randy, I've added you as collaborator.

**Comment by yuyichao** [comment]
Ping.

**Comment by randyzwitch** [comment]
Going to merge this, seems completely obvious. Will monitor for a fail, otherwise once it passes Travis then I'll validate #22

**Pull request merged**
